[package]
name = "rt_tour_1_5"
version = "0.1.0"
edition = "2021"

[dependencies]
arch_boot = { git = "ssh://git@github.com/shilei-massclouds/arch_boot.git" }
axhal = { git = "ssh://git@github.com/shilei-massclouds/axhal" }
pflash = { git = "ssh://git@github.com/shilei-massclouds/pflash" }
axlog2 = { git = "ssh://git@github.com/shilei-massclouds/axlog2" }
page_table = { git = "ssh://git@github.com/shilei-massclouds/page_table" }
axalloc = { git = "ssh://git@github.com/shilei-massclouds/axalloc" }

[target.'cfg(any(target_arch = "riscv32", target_arch = "riscv64"))'.dependencies]
riscv = "0.10"
