[package]
name = "rt_tour_3_1"
version = "0.1.0"
edition = "2021"

[dependencies]
arch_boot = { git = "ssh://git@github.com/shilei-massclouds/arch_boot.git" }
axhal = { git = "ssh://git@github.com/shilei-massclouds/axhal" }
axalloc = { git = "ssh://git@github.com/shilei-massclouds/axalloc" }
axlog2 = { git = "ssh://git@github.com/shilei-massclouds/axlog2" }
driver_common = { git = "ssh://git@github.com/shilei-massclouds/driver_common" }
driver_block = { git = "ssh://git@github.com/shilei-massclouds/driver_block" }
