[package]
name = "rt_tour_2_1"
version = "0.1.0"
edition = "2021"

[dependencies]
arch_boot = { git = "ssh://git@github.com/shilei-massclouds/arch_boot.git" }
axhal = { git = "ssh://git@github.com/shilei-massclouds/axhal" }
pflash = { git = "ssh://git@github.com/shilei-massclouds/pflash" }
axlog2 = { git = "ssh://git@github.com/shilei-massclouds/axlog2" }
page_table = { git = "ssh://git@github.com/shilei-massclouds/page_table" }
axalloc = { git = "ssh://git@github.com/shilei-massclouds/axalloc" }
axconfig = { git = "ssh://git@github.com/shilei-massclouds/axconfig" }
taskctx = { git = "ssh://git@github.com/shilei-massclouds/taskctx" }
spinbase = { git = "ssh://git@github.com/shilei-massclouds/spinbase" }

[target.'cfg(any(target_arch = "riscv32", target_arch = "riscv64"))'.dependencies]
riscv = "0.10"
sbi-rt = { version = "0.0.2", features = ["legacy"] }
