[package]
name = "rt_tour_5_1"
version = "0.1.0"
edition = "2021"

[dependencies]
arch_boot = { git = "ssh://git@github.com/shilei-massclouds/arch_boot.git" }
axhal = { git = "ssh://git@github.com/shilei-massclouds/axhal" }
axlog2 = { git = "ssh://git@github.com/shilei-massclouds/axlog2" }
axio = { git = "ssh://git@github.com/shilei-massclouds/axio" }
axtype = { git = "ssh://git@github.com/shilei-massclouds/axtype" }
elf = { git = "ssh://git@github.com/shilei-massclouds/elf" }
fileops = { git = "ssh://git@github.com/shilei-massclouds/fileops" }
