[package]
name = "rt_tour_1_3"
version = "0.1.0"
edition = "2021"

[dependencies]
arch_boot = { git = "ssh://git@github.com/shilei-massclouds/arch_boot.git" }
axhal = { git = "ssh://git@github.com/shilei-massclouds/axhal" }
axlog2 = { git = "ssh://git@github.com/shilei-massclouds/axlog2" }
page_table = { git = "ssh://git@github.com/shilei-massclouds/page_table" }
axalloc = { git = "ssh://git@github.com/shilei-massclouds/axalloc" }
