[package]
name = "rt_tour_3_2"
version = "0.1.0"
edition = "2021"

[dependencies]
arch_boot = { git = "ssh://git@github.com/shilei-massclouds/arch_boot.git" }
axhal = { git = "ssh://git@github.com/shilei-massclouds/axhal" }
axlog2 = { git = "ssh://git@github.com/shilei-massclouds/axlog2" }
driver_common = { git = "ssh://git@github.com/shilei-massclouds/driver_common" }
driver_block = { git = "ssh://git@github.com/shilei-massclouds/driver_block" }
page_table = { git = "ssh://git@github.com/shilei-massclouds/page_table" }
axdriver = { git = "ssh://git@github.com/shilei-massclouds/axdriver" }
