[package]
name = "rt_tour_3_3"
version = "0.1.0"
edition = "2021"

[dependencies]
arch_boot = { git = "ssh://git@github.com/shilei-massclouds/arch_boot.git" }
axhal = { git = "ssh://git@github.com/shilei-massclouds/axhal" }
axlog2 = { git = "ssh://git@github.com/shilei-massclouds/axlog2" }
axfile = { git = "ssh://git@github.com/shilei-massclouds/axfile" }
fstree = { git = "ssh://git@github.com/shilei-massclouds/fstree" }
