[package]
name = "rt_fstree"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
arch_boot = { git = "ssh://git@github.com/shilei-massclouds/arch_boot" }
axconfig = { git = "ssh://git@github.com/shilei-massclouds/axconfig" }
axlog2 = { git = "ssh://git@github.com/shilei-massclouds/axlog2" }
fstree = { git = "ssh://git@github.com/shilei-massclouds/fstree" }
axmount = { git = "ssh://git@github.com/shilei-massclouds/axmount" }
axhal = { git = "ssh://git@github.com/shilei-massclouds/axhal" }
