[package]
name = "rt_tour_4_4"
version = "0.1.0"
edition = "2021"

[dependencies]
arch_boot = { git = "ssh://git@github.com/shilei-massclouds/arch_boot.git" }
axhal = { git = "ssh://git@github.com/shilei-massclouds/axhal" }
axlog2 = { git = "ssh://git@github.com/shilei-massclouds/axlog2" }
page_table = { git = "ssh://git@github.com/shilei-massclouds/page_table" }
axalloc = { git = "ssh://git@github.com/shilei-massclouds/axalloc" }
axconfig = { git = "ssh://git@github.com/shilei-massclouds/axconfig" }
run_queue = { git = "ssh://git@github.com/shilei-massclouds/run_queue" }
wait_queue = { git = "ssh://git@github.com/shilei-massclouds/wait_queue" }
preempt_guard = { git = "ssh://git@github.com/shilei-massclouds/preempt_guard" }
mutex = { git = "ssh://git@github.com/shilei-massclouds/mutex" }
task = { git = "ssh://git@github.com/shilei-massclouds/task" }
fork = { git = "ssh://git@github.com/shilei-massclouds/fork" }
mmap = { git = "ssh://git@github.com/shilei-massclouds/mmap" }
fileops = { git = "ssh://git@github.com/shilei-massclouds/fileops" }

[target.'cfg(any(target_arch = "riscv32", target_arch = "riscv64"))'.dependencies]
riscv = "0.10"
sbi-rt = { version = "0.0.2", features = ["legacy"] }
